version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: easycorp/easyadmin-bundle
    versions:
    - 3.2.2
    - 3.2.3
    - 3.2.4
    - 3.2.5
    - 3.2.6
    - 3.2.7
    - 3.2.8
  - dependency-name: doctrine/doctrine-migrations-bundle
    versions:
    - 3.0.2
    - 3.1.0
  - dependency-name: symfony/validator
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/mime
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/console
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/yaml
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/notifier
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/process
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/intl
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/asset
    versions:
    - 5.2.2
    - 5.2.3
