#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
    entities:
        DiscordRole:
            class: App\Entity\DiscordRole
            disabled_actions: ['new','edit','delete']
            list:
                fields: ['id','name','characters','corporations','alliances']
        Character:
            class: App\Entity\Character
            disabled_actions: ['new']
            list:
                fields: ['id','Name','DiscordName','Roles']
            form:
                fields:
                    - { property: 'Name', type_options: { disabled: true }}
                    - { property: 'DiscordName', type_options: { disabled: true }}
                    - { property: 'DiscordMail', type_options: { disabled: true }}
                    - 'Roles'
        Corporation:
            class: App\Entity\Corporation
            disabled_actions: ['new']
            list:
                fields: ['id','Name','Roles']
            form:
                fields:
                    - { property: 'Name', type_options: { disabled: true }}
                    - 'Roles'
        Alliance:
            class: App\Entity\Alliance
            disabled_actions: ['new']
            list:
                fields: ['id','Name','Roles']
            form:
                fields:
                    - { property: 'Name', type_options: { disabled: true }}
                    - 'Roles'
    site_name: 'EVEAuth by nicti'
    user:
        name_property_path: 'Username'