#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
    entities:
        DiscordRole:
            class: App\Entity\DiscordRole
            disabled_actions: ['new']
            list:
                fields: ['id','name','characters','corporations','alliances']
            form:
                fields:
                    - { property: 'Name', type_options: { disabled: true }}
        Character:
            class: App\Entity\Character
            disabled_actions: ['new']
            list:
                fields: ['id','Name','DiscordName','Roles']
            form:
                fields:
                    - { property: 'Name', type_options: { disabled: true }}
                    - { property: 'DiscordName', type_options: { disabled: true }}
                    - { property: 'DiscordMail', type_options: { disabled: true }}
                    - 'Roles'
        Corporation:
            class: App\Entity\Corporation
            disabled_actions: ['new']
            list:
                fields: ['id','Name','Roles']
            form:
                fields:
                    - { property: 'Name', type_options: { disabled: true }}
                    - 'Roles'
        Alliance:
            class: App\Entity\Alliance
            disabled_actions: ['new']
            list:
                fields: ['id','Name','Roles']
            form:
                fields:
                    - { property: 'Name', type_options: { disabled: true }}
                    - 'Roles'
    site_name: 'EVEAuth by nicti Tenor'
    user:
        name_property_path: 'Username'
    design:
        menu:
            - {label: 'Discord'}
            - DiscordRole
            - {label: 'Pull Roles', url: '/admin/pullRoles', icon: 'download'}
            - {label: 'Push Roles', url: '/admin/pushRoles', icon: 'upload'}
            - {label: 'Setup Roles', url: '/admin/setupRoles', icon: 'tools'}
            - {label: 'EVE'}
            - Character
            - Corporation
            - Alliance